Repository DeutscheModelUnitedNations/munify-chase, pull requests merged in 2024-05, with the labels that each got.

#179 🐞 fix: Decrypt Git Crypt encrypted files and remove FontAwesome Package aspects from repo
  .github/workflows/build.yml
  .github/workflows/build_publish_container_images.yml
  Dockerfile.chase.backend
  Dockerfile.chase.frontend
  bunfig.toml
  chase/frontend/.npmrc
Labels: bug

#187 🐞 fix:(CHASE Frontend): fixed the line break issue in the version log
  bun.lockb
  chase/frontend/components/version_modal.tsx
  chase/frontend/package.json
Labels: bug

#190 ✨ feature: Adds the "nightly" branch and build which enables us to release separate nightly images for testing purposes
  .github/workflows/build_publish_container_images.yml
  bun.lockb
Labels: feature

#191 🧹 chore (App Frontend): Make sure cross-scripting is not possible through github changelog entries
  bun.lockb
  chase/frontend/components/version_modal.tsx
  chase/frontend/package.json
Labels: enhancement
