Repository DeutscheModelUnitedNations/munify-chase, pull requests merged in 2025-05, with the labels that each got.

#228 ✨ feature: add speaker time stats tracking
  drizzle/0001_romantic_shape.sql
  drizzle/meta/0001_snapshot.json
  drizzle/meta/_journal.json
  schema.graphql
  src/api/db/relations.ts
  src/api/db/schema.ts
  src/api/handlers/speakersList.ts
  src/lib/components/speakersList/ChairSpeakersQueue.svelte
  src/lib/components/speakersList/PresentationSpeakersQueue.svelte
  src/lib/utils/import.ts
Labels: feature

#262 🐞 fix: Update prose leading class for consistent text styling in Whiteboard
  src/lib/components/whiteboard/WhiteboardEditor.svelte
  src/lib/components/whiteboard/WhiteboardViewer.svelte
Labels: bug

#264 🐞 fix: unique NSA and UN entries
  schema.graphql
  src/api/db/relations.ts
  src/api/handlers/agendaItem.ts
  src/api/handlers/conference.ts
  src/lib/components/speakersList/ChairSpeakersQueue.svelte
  src/lib/helpers/distinguishConferenceMembers.ts
  src/routes/app/(launcher)/+page.svelte
  src/routes/app/(launcher)/import/+page.svelte
  src/routes/app/[conferenceId]/[committeeId]/(chairs)/+layout.gql
  src/routes/app/[conferenceId]/[committeeId]/(chairs)/committeeSubscription.ts
  src/routes/app/[conferenceId]/[committeeId]/(chairs)/presence/+page.svelte
  src/routes/app/[conferenceId]/[committeeId]/(presentation)/+page.gql
  src/routes/app/[conferenceId]/[committeeId]/(presentation)/committeeSubscription.ts
Labels: bug

#263 🐞 fix: Refactor agenda item handling and add createAgendaItem mutation in GraphQL
  .github/workflows/build_run.yml
  messages/de.json
  schema.graphql
  src/api/db/schema.ts
  src/api/handlers/agendaItem.ts
  src/lib/components/committee/AgendaItemChanger.svelte
  src/lib/components/whiteboard/WhiteboardEditor.svelte
  src/lib/helpers/nanoid.ts
  src/routes/app/(launcher)/import/+page.svelte
Labels: enhancement

#266 ✨ feat: add committee topic tracker
  drizzle/0002_ambiguous_felicia_hardy.sql
  drizzle/0002_panoramic_agent_brand.sql
  drizzle/meta/0002_snapshot.json
  drizzle/meta/_journal.json
  src/api/db/relations.ts
  src/api/db/schema.ts
  src/api/handlers/committee.ts
Labels: feature
